baseURL = "https://oss-in-energy.github.io/oss-in-energy/"
languageCode = "en-us"
theme = "hyde"
title = "Open-Source in Energy"

[params]
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-09"
description = "A collection of Open-source projects for the energy sector"

[author]
name = "ACS (RWTH Aachen)"
page = "https://www.acs.eonerc.rwth-aachen.de"

[Menus]
main = [
    {Name = "Github", URL = "https://github.com/oss-in-energy/oss-in-energy"},
]