baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hyde"
title = "Open Source in Energy"
custom_css = ["css/custom.css"]
[params]
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-09"