name: website

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install requirements
        run: pip install -r requirements.txt
        working-directory: parser
      - name: create table
        run: python parser/yaml_to_html.py projects.yaml
        env:
          GITHUB_API_KEY: ${{ secrets.GH_API_KEY }}
      - run: sudo apt-get install -y hugo
      - name: generate page
        run: |
         hugo -D
      - name: Copy csv into website resources folder
        run: cp table.csv public
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  publish_website:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download website artifact
        uses: actions/download-artifact@v2
      - name: Deploy to GitHub Pages
        # if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}