name: website

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install requirements
        run: pip install -r requirements.txt
        working-directory: parser
      - name: create table
        run: python yaml_to_html.py
        working-directory: parser
      - run: ls -lah parser
      - run: sudo apt-get install -y hugo
      - name: generate page
        run: |
         hugo -D
      - run: ls -lah public
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}